---
- name: Check if docker is already installed
  stat:
    path: /usr/bin/docker
  register: docker

- name: Install docker
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  when: not docker.stat.exists

- name: Copy nextjs dockerfile to server
  copy:
    src: Dockerfile.nextjs
    dest: "{{ ansible_env.HOME }}/Dockerfile.nextjs"

- name: Copy caddy dockerfile to server
  copy:
    src: Dockerfile.caddy
    dest: "{{ ansible_env.HOME }}/Dockerfile.caddy"

- name: Copy docker compose to server
  copy:
    src: docker-compose.yml
    dest: "{{ ansible_env.HOME }}/docker-compose.yml"
