apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - sealed-secrets-controller.yaml
  - sealed-secrets-porkbun-key.yaml
  - sealed-secrets-porkbun-secret-key.yaml
  - traefik-configmap.yaml
patches:
  - path: traefik-deployment-patch.yaml
