---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: porkbun-secret-key
  namespace: default
spec:
  encryptedData:
    porkbun-secret-key: AgCMe+G9KmJKT8FHjT/Pe9CCqgVZWK+kDexmbbggMxJrUkPv35hjHkOUJY0sIO5/BsW6fZmWtgKhNOzjFYmnVpoG8FMv/nQND5+NtIAd9ek29aS/MI6oNFno1oIvZhRQZjGB1aFFhkhE0e5NxrygL7tB/Fx1oKOfpa+FEe/ZwuXPOzjVGr8KQ6eJJC3uz40ijqlhQHPlN0xwRPoZCIfKH+UuOgrPpn3uyWV9OAVFmJyFyYkqzRXIKHiQWQt1htvBjnEc16j/D9pldfHW7q1TJ9/I1O+wypGCmip+ULDjHAj2rnjQzhbFUqkBcTuxaeoWp2mYX1R97lvY54nBzB1ASPt8ebiSPgHg/zrKA9hm4GLUryHa9J6qJ7dRVSOYkyFsJZd4YD2GG5+YJBVAwi5M9/NNLNNK2z4bbq+R0DILNRpk+S0kSp+SWl60jlpQ5GSk2KAvzsKmoH3yH/F6Oi2QR1zg9xqvCSBgvbN414AUVLk09XLm6hSx5kLhFd3WUolKO7WvkNyR6Yb6jM/I5S5ifSORdCOpL2n4/w+XVGGuxpbaE3WJVw/D2NJDGHC0vV9A72hmuThzJMGQvU2KpoZKNiSwT7tF717x6w+uQB7oku4rlKtg1CeaUK0JY2/7enlYtnCTukR0U0Tf4HRdadhT3b2LG/TLy79tTAGO4pgXORJLDzXeQvUCDtJQ1BjtBn/5f6wTNT8dp0EwNgdxWl4x4UyaBF3I/73rQfVr9S6D5aw6zDXX3hwP/I75fl6Y/moOkeBJ21ahYntxhVRBMuyneOlpy9jw4Q==
  template:
    metadata:
      creationTimestamp: null
      name: porkbun-secret-key
      namespace: default
