---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: porkbun-secret-key
  namespace: default
spec:
  encryptedData:
    PORKBUN_SECRET_API_KEY: AgCh+5nEMedwZtZg/4PGpdfeIV2zDRYHoLqWKWGbxgTjpr04ZuePrWp5waXkWB4JrFCX7kQScUmxF+G9cFU6kFbGNumJCG5OVKOa6P8KUEj6Hq3EAi/jfE4gL3UkPov5j92Mjc4OPKrowwIw6MYzAbSfZU4ijxOLqJnqOMMCF+UFCZOLCjGCYyK1licEWx+gWV6A0fQqRrfMYVephdpxRsOioxc1I3us4LNEhVeKbUWNwfEdai9eKriBJ6hhBfT1465LVnQvp6FRS6OSC1aWhkh12tbzuzCRM4CvVGUOOinYKviEJC23UDTt9B/Zt+xfbuvHj8BKa6kNn33R/rLpbKUCha16HLR7ufsHEFzbs8v91SX2YKSp217bPSJs9FYZ/9QEvP0YBBpcOk2pQzSKcJBoC4IFjqO/4CC6ZYK36uX8WCDcUHTjg1hW1AG44Fr5LDj5//y1wjYy6tPmVq/DVFaNDF3jJ5MG1F/d5jvXZZ6FFt1+4CngybIj3PDGldeHt0A6HYTSxurduKompbb7yAbNIDLmZdlzmJk2ZnGhWVlby1WJQg4TXlTV3h1Sj/uQP7ZRCiHbNFLxsUQfjUm7I+rwW5cFMDcJ7C9rdz1gVlwfQcv+scdRaNfGo0nklz8fvggB0+5uegdkeFrggVB5sZsMHjcVqOyuljVI1E+BM1dDIbWW4WKboGJ71UfBNBdLQd28T3ctwRRbP3PKn9zcVU9Ga3lTWuLcWbTP+BhRZUT8XH67snh3t3IttauwMXEQKXBsjUyxNV7p/OgI7W2q0dA5Np9uBg==
  template:
    metadata:
      creationTimestamp: null
      name: porkbun-secret-key
      namespace: default
