---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: porkbun-key
  namespace: default
spec:
  encryptedData:
    PORKBUN_API_KEY: AgAmTKmZd2k0T5qO8VevE+WC5jSArIppm3u7ps6Hrr0aHABdI/PeQg2nFcufZHAfMhXfPwbhSXY75U6HavJI9C/+9YUGMx/5rbYWguPLVCV2pwcEsbJPyUSqkIOK40u01LjgpDxpB1d5IMYmHOGP3s1EcW+clNGssA+ny1IhF0bkeXRwSgOPuCWYR1Ntos7WtOxMB1kQnfO4uH1JIMai+Uf1LyPSNqic/4EsA/0pqLSgdmrxEM09koKHo2aUJIN8h5KPLvab9V7vonLfAIg3o3+7cxvN7ul79r3u5D6gPydWOLrwlyGQbo+osJBLKVoBYgvyTciJF9k/JOdSl5aT3AZ14hPxsdqUm4kIMrzOc8gaNd/iDrD/eDHNANMYo3n3TDmd5Iza0cbR7+50WryLBFiup0auL8qTEpVDm7IYr8G/yO7Rvkpb1pEEMmo70FlDNk26DhHNibku1dUrX9kp1SoSrOO9KMk4IXeVTArSGL2MwKJ2wJBxErXFfz4dzSx/yawQ9cqoSZLq2CQ6rYGidXiRb8g0fr0FlKYBxbnVF22J7Mg7lOfE1ycezasunWhytKYWaHrPLTRpyCmllUwa06FxP5jVTIIMEI0CdFktjBqW0mLo8Y1TrN944Af5c992YXNuY6hN12fzq+dReamN1pM5/O+D+YWZgBU8g+j2tE7Mw9l/mqd0kbdtISJH19FweDUxr2vsHw6LGFMUJQe9URNINSCZvAt6EA4dMg6na0BmUv68wr2YV6605GR54hA1yXD0nqHwxiLzr7o9MhreA2hot/67cQ==
  template:
    metadata:
      creationTimestamp: null
      name: porkbun-key
      namespace: default
