apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: traefik
          image: traefik:v3.3
          envFrom:
          - secretRef:
              name: porkbun-key
          - secretRef:
              name: porkbun-secret-key
          args:
            - --accessLog
            - --providers.kubernetescrd
            - --entryPoints.web.address=:80
            - --entryPoints.web.http.redirections.entryPoint.to=websecure
            - --entryPoints.web.http.redirections.entryPoint.scheme=https
            - --entryPoints.web.http.redirections.entryPoint.permanent=true
            - --entryPoints.websecure.address=:443
            - --certificatesResolvers.myresolver.acme.email=chevannes.kai@gmail.com
            - --certificatesResolvers.myresolver.acme.storage=acme.json
            - --certificatesResolvers.myresolver.acme.dnsChallenge.provider=porkbun
