apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: default
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: traefik
          image: traefik:v3.3
          envFrom:
          - secretRef:
              name: porkbun-key
          - secretRef:
              name: porkbun-secret-key
          args:
            - --accessLog
            - --providers.kubernetescrd
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --certificatesResolvers.myresolver.acme.email=chevannes.kai@gmail.com
            - --certificatesResolvers.myresolver.acme.storage=acme.json
            - --certificatesResolvers.myresolver.acme.dnsChallenge.provider=porkbun
            - --certificatesResolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
