services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - portfolio_network
    depends_on:
      - reverse_proxy

  reverse_proxy:
    build:  
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - '80:80'
      - '443:443'
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
