kind: Deployment
apiVersion: apps/v1
metadata:
  name: portfolio
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: myregistry.localhost:5000/kaichevannes/portfolio
        name: portfolio
        ports:
          - name: web
            containerPort: 3000
