---
- name: Install Go
  include_tasks: install_go.yml

- name: Install xcaddy
  become: true
  shell: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
  environment:
    PATH: $PATH:/usr/local/go/bin
    GOPATH: "{{ ansible_env.HOME }}/go"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/go/bin/xcaddy"

- name: Check if caddy is installed
  stat:
    path: /usr/local/bin/caddy
  register: caddy

- name: Setup caddy
  when: not caddy.stat.exists
  block:
  - name: Build caddy with porkbun
    become: true
    shell: xcaddy build latest --with github.com/caddy-dns/porkbun
    environment:
      PATH: "$PATH:/usr/local/go/bin/:{{ ansible_env.HOME }}/go/bin"

  # - name: Move caddy to local binaries
  #   become: true
  #   ansible.builtin.command:
  #     cmd: "mv {{ ansible_env.HOME }}/caddy /usr/local/bin/caddy"

- name: Copy Caddyfile to server
  template:
    src: Caddyfile.j2
    dest: "{{ ansible_env.HOME }}/Caddyfile"
