apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portfolio
  namespace: default
spec:
  interval: 60s
  path: ./cluster/manifest/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: portfolio
