apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: portfolio
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
    url: https://github.com/kaichevannes/portfolio.git
