kind: Deployment
apiVersion: apps/v1
metadata:
  name: portfolio
  namespace: default
  labels:
    app: portfolio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  strategy: {}
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - image: ghcr.io/kaichevannes/portfolio:e1055318fa8c3241f363e85b11637be02d636120
        name: portfolio
        ports:
          - name: web
            containerPort: 3000
