kind: Deployment
apiVersion: apps/v1
metadata:
  name: portfolio
  namespace: default
  labels:
    app: portfolio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  strategy: {}
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - image: ghcr.io/kaichevannes/portfolio:426b74ea91b7d85d51116a0b4b7ded8ab2c42e68
        name: portfolio
        ports:
          - name: web
            containerPort: 3000
