apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: default

spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      nodePort: 30080
    - name: websecure
      port: 443
      nodePort: 30443
  selector:
    app: traefik
