apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: default

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web
    - port: 443
      targetPort: websecure
  selector:
    app: traefik
