---
- name: Install unzip
  become: true
  package: name=unzip state=present

- name: Install Bun
  shell: curl -fsSL https://bun.sh/install | bash

- name: Add Bun to path
  become: true
  lineinfile:
    path: /etc/profile
    line: "export PATH={{ ansible_env.HOME }}/.bun/bin:$PATH"
    create: yes
