name: Lint Code Base

on:
  pull_request:
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.1.0
        env:
          FILTER_REGEX_INCLUDE: ^src/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
