name: release

on:
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: portfolio
  DEPLOY_FILE_PATH: cluster/manifest/base/portfolio/deployment.yml

jobs:
  
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: docker/setup-buildx-action@v3.10.0
      - name: Build image
        run: |
          IMAGE_ID=ghcr.io/kaichevannes/$IMAGE_NAME

          docker buildx build \
          --file Dockerfile \
          --tag $IMAGE_ID:${{ github.sha }} \
          --tag $IMAGE_ID:latest \
          --platform linux/arm64,linux/amd64 \
          --cache-from $IMAGE_ID:latest \
          --push \
          .

      - name: Update image tag
        run: |
          sed -i "s|image.*|image: ghcr.io/kaichevannes/portfolio:${{ github.sha }}|" $DEPLOY_FILE_PATH
          
      - name: Push deployment manifest
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email  'github-actions[bot]@users.noreply.github.com'
          git commit -am "GITHUB ACTION: update deployment manifest to new sha"
          git push
