name: release

on:
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: portfolio
  DEPLOY_FILE_PATH: cluster/manifest/base/portfolio/deployment.yml

jobs:
  
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build . \
          --file Dockerfile \
          --tag $IMAGE_NAME \
          --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          COMMIT_SHA=${{ github.sha }}

          echo IMAGE_ID=$IMAGE_ID
          echo COMMIT_SHA=$COMMIT_SHA

          docker tag $IMAGE_NAME $IMAGE_ID:$COMMIT_SHA
          docker push $IMAGE_ID:$COMMIT_SHA

      - name: Update image tag
        run: |
          sed -i "s|image.*|image: ghcr.io/kaichevannes/portfolio:test|" $DEPLOY_FILE_PATH
          
      - name: Push deployment manifest
        run: |
          git config user.name ${{ github.actor }}
          git config user.email  "${{ github.actor }}@users.noreply.github.com"
          git commit -am "GITHUB ACTION: update deployment manifest to new sha"
          git push
